services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    volumes:
      - aponti-overlay
    
    secrets: [db_password]
    
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      
      resources:
        limits: {
          cpus: "0.50",
          memory: 512M
        }

  product-service:
    image: aponti/product-service:1.0
    environment:
      PORT:
      DB_HOST:
      DB_PORT:
      DB_NAME:
      DB_USER:
      DB_PASSWORD_FILE: /run/secrets/db_password
    
    networks:
      - aponti-overlay

    secrets:
      - db_password

    deploy:
      replicas: 3

      restart_policy: {
        condition: on-failure
      }

      update_config:
        order: start-first
        parallelism: 1
        delay: 10s

      resources:
        limits: {
          cpus: "0.25",
          memory: 128M
        }

  inventory-service:
    image: aponti/inventory-service:1.0
    environment:
      PORT: "3002"
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD_FILE: /run/secrets/db_password
    
    networks:
      - aponti-overlay

    secrets:
      - db_password

    deploy:
      replicas: 3

      restart_policy: {
        condition: on-failure
      }

      update_config:
        order: start-first
        parallelism: 1
        delay: 10s

      resources: 
        limits: {
          cpus: "0.25",
          memory: 128M
        }

  order-service:
    image: aponti/order-service:1.0
    environment:
      PORT: "3003"
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD_FILE: /run/secrets/db_password

    networks:
      - aponti-overlay

    secrets:
      - db_password

    deploy:
      replicas: 3

      restart_policy: {
        condition: on-failure
      }

      update_config:
        order: start-first
        parallelism: 1
        delay: 10s

      resources: 
        limits: {
          cpus: "0.25",
          memory: 128M
        }